---
- name: Find EPG bindings
  hosts: apic
  connection: local
  gather_facts: false
  vars:
    target_node: "101"
    target_port: "10"
    target_tenant: Demo_Tenant
    target_app_profile: Demo_App
    pod_id: "1" 
    common_args: &common_args
      host: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      validate_certs: false

  tasks:
    - name: Get EPG Hierarchy
      cisco.aci.aci_epg:
        <<: *common_args
        tenant: "{{ target_tenant }}"
        app_profile: "{{ target_app_profile }}"
        state: query
      register: all_epgs

    - name: Find static bindings on the port
      cisco.aci.aci_static_binding_to_epg:
        <<: *common_args
        tenant: "{{ target_tenant }}"
        app_profile: "{{ target_app_profile }}"
        epg: "{{ item.fvAEPg.attributes.name }}"
        pod_id: "{{ pod_id }}"
        leafs: "{{ target_node }}"
        interface: "1/{{ target_port }}"
        state: query
      loop: "{{ all_epgs.current[0].fvAp.children }}"
      register: binding_query
      loop_control:
        label: "Checking EPG: {{ item.fvAEPg.attributes.name }}"

    - name: Save results
      ansible.builtin.set_stats:
        data:
          binding_results: "{{ binding_query }}"

    - name: Show detected bindings
      debug:
        msg: "FOUND: EPG '{{ item.item.fvAEPg.attributes.name }}' is bound to Node {{ target_node }}, Port 1/{{ target_port }}"
      loop: "{{ binding_query.results }}"
      when: item.current | default([]) | length > 0
      loop_control:
        label: "{{ item.item.fvAEPg.attributes.name }}"
